### ISSUE TITLE
在 /home 和 /dev 下执行ls命令引发错误

### ISSUE THREAD

**Issue by 52871299hzy** [ForkKILLET/SudoerOfMyself#6]
如题，在 /home 和 /dev 下执行ls命令都会引发错误，在/bin中则不会。不影响cd和cat等。

```
$ pwd
/
$ ls /home
core dumped: Cannot read properties of undefined (reading '0')
$ ls /dev
core dumped: Cannot read properties of undefined (reading '0')
```
F12控制台报错：
```
TypeError: Cannot read properties of undefined (reading '0')
    at command.js:229:49
    at Array.filter (<anonymous>)
    at Object.ls [as func] (command.js:229:31)
    at term.startLoop (loop.js:89:16)
```
浏览器：Chromium103.0.5060.134
[存档json](https://pastebin.com/GK6GEjXb)

附加信息：
```
$ ls -al /home
drwxr-x--- myself undefined
drwxr-x--- myself undefined
-rwxr-x--- myself .history
$ ls -al /dev 
crw-rw-rw- root   undefined
brw-rw---- root   undefined
brw-rw---- root   undefined
```

**Comment by ACnoway** [comment]
这个是个老bug了，叉子现在好像没时间改（至少上次问他的时候是这么说的）

**Comment by ForkKILLET** [comment]
> 这个是个老bug了，叉子现在好像没时间改（至少上次问他的时候是这么说的）

确实，exlg 写完应该就有空修了

**Comment by Augury461** [comment]
第四关是如何通过的啊/yun

**Comment by SteveZMTstudios** [comment]
手机端稳定触发
![Screenshot_2025-02-07-13-27-50-019_com.android.chrome.jpg](https://github.com/user-attachments/assets/3a357716-1d2d-48df-b95e-f6054f35ee7f)
